# Generated by Django 5.2.3 on 2025-08-29 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('participants', models.TextField(default='[]')),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_by', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Accommodation', 'Accommodation'), ('Transport', 'Transport'), ('Food & Dining', 'Food & Dining'), ('Drinks', 'Drinks'), ('Activities & Entertainment', 'Activities & Entertainment'), ('Shopping & Souvenirs', 'Shopping & Souvenirs'), ('Emergency / Medical', 'Emergency / Medical'), ('Tips & Service Charges', 'Tips & Service Charges'), ('Other', 'Other')], default='Other', max_length=50)),
                ('custom_category', models.CharField(blank=True, max_length=100)),
                ('payment_mode', models.CharField(choices=[('UPI', 'UPI'), ('Cash', 'Cash'), ('Card', 'Card')], default='Cash', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='trip.trip')),
            ],
        ),
    ]
