"""
Django settings for tripbudgetmonitor project.

Generated by 'django-admin startproject' using Django 5.2.3.
"""

import os
from pathlib import Path
import dj_database_url

# ---------------------------
# Base directory
# ---------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# ---------------------------
# Security
# ---------------------------
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-+$rt(^rw!yr9r#9&86w=0-@pr2(firwt(b_=ipkkm8okc%3k07",
)

DEBUG = os.environ.get("DEBUG", "True") == "True"

ALLOWED_HOSTS = [
    "tripbudgetmonitor.onrender.com",
    "tripbudgetmonitor-dx6d.onrender.com",
    "localhost",
    "127.0.0.1",
]

# ---------------------------
# Installed apps
# ---------------------------
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "trip",
    "accounts",
]

# ---------------------------
# Middleware
# ---------------------------
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Static files in prod
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "tripbudgetmonitor.urls"

# ---------------------------
# Templates
# ---------------------------
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    }
]

WSGI_APPLICATION = "tripbudgetmonitor.wsgi.application"

# ---------------------------
# Database
# ---------------------------
if DEBUG:
    # Use SQLite for local development
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    # Use PostgreSQL in production
    DATABASES = {
        "default": dj_database_url.config(
            default="postgresql://neondb_owner:npg_PqY6VMNE3otS@ep-fragrant-waterfall-a1k4ey8v-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require",
            conn_max_age=600,
            ssl_require=True,
        )
    }

# ---------------------------
# Password validation
# ---------------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# ---------------------------
# Internationalization
# ---------------------------
LANGUAGE_CODE = "en-us"
TIME_ZONE = "Asia/Kolkata"
USE_I18N = True
USE_TZ = True

# ---------------------------
# Static & media files
# ---------------------------
STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]  # Local static files
STATIC_ROOT = BASE_DIR / "staticfiles"    # Collected static files
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# ---------------------------
# Default primary key
# ---------------------------
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ---------------------------
# Login
# ---------------------------
LOGIN_URL = "/accounts/login/"

# ---------------------------
# HTTPS / Security Cookies
# ---------------------------
SECURE_SSL_REDIRECT = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG

# ---------------------------
# Optional: PWA Service Worker
# ---------------------------
# Place your service worker in /static/js/service-worker.js
# Make sure to add it in your base template:
# <script>
#   if ('serviceWorker' in navigator) {
#       navigator.serviceWorker.register("{% static 'js/service-worker.js' %}");
#   }
# </script>
